#  AdminUser.create!(email: 'marco03@bk.ru', password: 'J8s5c28N68h',
#                     password_confirmation: 'J8s5c28N68h')

#  ManHairCut.create(title: "Окантовка", price: 250)
#  ManHairCut.create(title: "Корректировка усов", price: 100)
#  ManHairCut.create(title: "Корректировка бороды", price: 250)
#  ManHairCut.create(title: "Коррекция бровей", price: 50)
#  ManHairCut.create(title: "Льготная стрижка по будням (с 9:00 до 11:00)", price: 300)
#  ManHairCut.create(title: "Стрижка под машинку (наголо)", price: 200)
#  ManHairCut.create(title: "Стрижка под 1 насадку", price: 300)
#  ManHairCut.create(title: "Стрижка спортивная", price: 500)
#  ManHairCut.create(title: "Стрижка модельная", price: 550)
#  ManHairCut.create(title: "Стрижка креативная", price: 650)
#  ManHairCut.create(title: "Стрижка детская до 7 лет", price: 400)
#  ManHairCut.create(title: "Укладка волос", price: 200)
#  ManHairCut.create(title: "Сушка волос", price: 100)
#  ManHairCut.create(title: "Мытьё головы", price: 100)
#  ManHairCut.create(title: "Гель, лак", price: 100)

#  Depilation.create(title: "Подмышки (воск-сахар)", price: "350-400")
#  Depilation.create(title: "Голени (с коленом и пальчиками)", price: "700")
#  Depilation.create(title: "Бёдра (с коленом и пальчиками)", price: "700")
#  Depilation.create(title: "Ноги полностью", price: "1000-1200")
#  Depilation.create(title: "Руки полностью", price: "700")
#  Depilation.create(title: "Руки до локтя", price: "400")
#  Depilation.create(title: "Руки от локтя до плеча", price: "400")
#  Depilation.create(title: "Бикини глубокое (сахар/воск) без подстригания волос", price: "1000-1200")
#  Depilation.create(title: "Бикини глубокое (сахар/воск) с подстриганием волос", price: "1100-1450")
#  Depilation.create(title: "Усики", price: "150-350")
#  Depilation.create(title: "Подбородок", price: "от 200")
#  Depilation.create(title: "Удаление волос в носу", price: "от 250")
#  Depilation.create(title: "Удаление волос в ушах", price: "от 250")
#  Depilation.create(title: "Бакенбарды", price: "250-400")
#  Depilation.create(title: "Удаление волос на шее и затылке", price: "от 500")
#  Depilation.create(title: "Дорожка на животе", price: "от 200")

#  Makeup.create(title: "Ламинирование ресниц с окрашиванием", price: "2000")
#  Makeup.create(title: "Окрашивание ресниц (краска/хна)", price: "450")
#  Makeup.create(title: "Ламинирование бровей", price: "1300")
#  Makeup.create(title: "Ламинирование бровей + коррекция и окрашивание", price: "1900")
#  Makeup.create(title: "Окрашивание бровей хна + коррекция", price: "1000")
#  Makeup.create(title: "Окрашивание бровей краской + коррекция", price: "800")
#  Makeup.create(title: "Макияж", price: "от 2500")
#  Makeup.create(title: "Укладка", price: "от 2500")
#  Makeup.create(title: "Экспресс макияж", price: "от 1500")
#  Makeup.create(title: "Блеск тату", price: "от 250")
#  Makeup.create(title: "Коррекция бровей (воск/пинцет)", price: "400")
#  Makeup.create(title: "Окрашивание бровей (без коррекции и архитектуры) краской", price: "450")
#  Makeup.create(title: "Окрашивание бровей (без коррекции и архитекутры) хной", price: "600")
#  Makeup.create(title: "Уходовая процедура для бровей (очищение, скрабирование, питание и увлажнение)", price: "400")
#  Makeup.create(title: "Уходовая процедура для ресниц", price: "400")

#  Manicure.create(title: "Маникюр без покрытия", price: 500)
#  Manicure.create(title: "Маникюр + однотонное покрытие", price: 1200)
#  Manicure.create(title: "Маникюр + легкий дизайн", price: 1400)
#  Manicure.create(title: "Наращивание", price: 1700)
#  Manicure.create(title: "Наращивание (свыше 3)", price: 1900)
#  Manicure.create(title: "Коррекция (не позднее 5 недель)", price: 900)
#  Manicure.create(title: "Простой рисунок", price: 300)
#  Manicure.create(title: "Сложный рисунок(геометрия/френч)", price: 500)
#  Manicure.create(title: "Стемпинг (ноготь)", price: 70)
#  Manicure.create(title: "Наклейка (ноготь)", price: 40)
#  Manicure.create(title: "Починка ногтя", price: 100)
#  Manicure.create(title: "Детский маникюр", price: 400)
#  Manicure.create(title: "Мужской маникюр", price: 700)
#  Manicure.create(title: "Укрепление ногтей (акриловая пудра)", price: 300)

#  Pedicure.create(title: "Педикюр без покрытия(пальчики)", price: 800)
#  Pedicure.create(title: "Педикюр + гель-лак(пальчики) однотонные", price: 1100)
#  Pedicure.create(title: "Педикюр(пальчики + ступни)", price: 1100)
#  Pedicure.create(title: "Педикюр(пальчики + ступни + гель-лак)", price: 1500)
#  Pedicure.create(title: "Снятие лака", price: 50)
#  Pedicure.create(title: "Снятие гель-лака", price: 200)

#  WomenHairCut.create(title: "Выравнивание челки, начес", price_lower_ten: "200", price_ten_to_twenty: "200", price_upper_twenty: "200")
#  WomenHairCut.create(title: "Стрижка льготная с сушкой (с 9:00 до 11:00 по будням)", price_lower_ten: "400", price_ten_to_twenty: "400", price_upper_twenty: "400")
#  WomenHairCut.create(title: "Стрижка льготная без сушки (с 9:00 до 11:00 по будням)", price_lower_ten: "300", price_ten_to_twenty: "300", price_upper_twenty: "300")
#  WomenHairCut.create(title: "Стрижка детская до 7 лет", price_lower_ten: "400", price_ten_to_twenty: nil, price_upper_twenty: nil)
#  WomenHairCut.create(title: "Стрижка модельная", price_lower_ten: "500", price_ten_to_twenty: nil, price_upper_twenty: nil)
#  WomenHairCut.create(title: "Стрижка \"каскад\", \"каре\"", price_lower_ten: "550", price_ten_to_twenty: "600", price_upper_twenty: "650")
#  WomenHairCut.create(title: "Стрижка креативная", price_lower_ten: "800", price_ten_to_twenty: "900", price_upper_twenty: nil)
#  WomenHairCut.create(title: "Выравнивание волос одним срезом", price_lower_ten: "500", price_ten_to_twenty: "500", price_upper_twenty: "500")
#  WomenHairCut.create(title: "Укладка волос (феном)", price_lower_ten: "350", price_ten_to_twenty: "450", price_upper_twenty: "550")
#  WomenHairCut.create(title: "Укладка волос (щипцами)", price_lower_ten: "от 1000", price_ten_to_twenty: nil, price_upper_twenty: nil)
#  WomenHairCut.create(title: "Химическая завивка", price_lower_ten: "1100", price_ten_to_twenty: "1400", price_upper_twenty: "1600")
#  WomenHairCut.create(title: "Осветление", price_lower_ten: "600", price_ten_to_twenty: "800", price_upper_twenty: "1200")
#  WomenHairCut.create(title: "Окраска корней волос", price_lower_ten: "500", price_ten_to_twenty: "600", price_upper_twenty: "750")
#  WomenHairCut.create(title: "Окраска волос в один тон", price_lower_ten: "550", price_ten_to_twenty: "650", price_upper_twenty: "850")
#  WomenHairCut.create(title: "Мелирование на шапочку", price_lower_ten: "1100", price_ten_to_twenty: "1300", price_upper_twenty: "1500")
#  WomenHairCut.create(title: "Мелирование на фольгу", price_lower_ten: "1300", price_ten_to_twenty: "1700", price_upper_twenty: "2100")
#  WomenHairCut.create(title: "Состав для химической завивки", price_lower_ten: "300", price_ten_to_twenty: "400", price_upper_twenty: "500")
#  WomenHairCut.create(title: "Осветляющий порошок IGORA", price_lower_ten: "1 норма - 550", price_ten_to_twenty: "Де-люкс - 650", price_upper_twenty: "Де-люкс - 650")
#  WomenHairCut.create(title: "Краска ESTEL", price_lower_ten: "450", price_ten_to_twenty: "Де-люкс - 650", price_upper_twenty: "Де-люкс - 650")
#  WomenHairCut.create(title: "Мытье головы", price_lower_ten: "150", price_ten_to_twenty: "200", price_upper_twenty: "250")
#  WomenHairCut.create(title: "Сушка волос", price_lower_ten: "150", price_ten_to_twenty: "200", price_upper_twenty: "300")
#  WomenHairCut.create(title: "Гель, лак", price_lower_ten: "120", price_ten_to_twenty: "120", price_upper_twenty: "150")